package ucip;

/*
 * File name:BaseUCIPRequest.java
 * Copyright:Copyright 2004-2006 Huawei Tech. Co. Ltd. All Rights Reserved
 * Description:
 * Modify by:
 * Modify time: YYYY-MM-DD
 * Tracking ID:
 * Modify content:
 */

import java.util.Date;

/**
 * <p>Title:  </p>
 * <p>Description:  </p>
 * <pre>  </pre>
 * <p>Copyright: Copyright 1998-2007,  All rights reserved</p>
 * <p>Company: Huawei Technologies Co., Ltd. </p>
 * @author q43637
 * @version V1.0 2007-7-25
 * @since
 */
public class BasicUCIPRequest
{
    /**
     * The originNodeType parameter defines the origin node type that is set by
     * the Charging System or provided by an external network element. It contains
     * the type of the logical node from where the operation originated. External
     * network elements are indicated by EXT and are not allowed to use the other
     * reserved names
     * Type:string
     * Value:
     * EXT External system
     * AIR Account information and refill
     * ADM Administrative system
     * UGW USSD gateway
     * IVR Interactive voice response system
     * OGW On-line gateway
     * SDP Service data point
     */
    private String originNodeType;
    
    /**
     * The originHostName parameter contains an identifier string for the host where
     * the operation originated from. The host name shall be unique within the
     * network for a given network element type.
     * Type:string
     * Length:1-255
     */
    private String originHostName;
    
    /**
     * The originTransactionID parameter reference to a single operation, generated by
     * the system it was initiated from. Together with originTimeStamp a unique
     * identification is provided.
     * Type:string
     * Length:1-20
     */
    private String originTransactionID;
    
    /**
     * The originTimeStamp parameter contains the time of sending the request by
     * the entity that initiated the operation.
     * Type:<dateTime.iso8601>
     */
    private Date originTimeStamp;
    
    /**
     * The subscriberNumberNAI parameter contains the Nature of Address Indicator
     * identifies the format of the Subscriber Number.
     * Type:i4
     * Value:
     * 0 Unknown
     * 1 International number
     * 2 National significant number
     * 3 Network specific number
     * 4 Subscriber number
     * 5 Reserved
     * 6 Abbreviated Number
     * 7 Reserved for extension
     * Optional
     */
    
    private int subscriberNumberNAI = 2;
    //Default is set to "National significant number" e.g. 102222222

    
    /**
     * The subscriberNumber parameter contains the subscriber identity of the
     * subscriber related to the operation. The default format of the parameter is the
     * same numbering format as used by the account database, this also includes
     * support of leading zeroes. If another format is used then it must be indicated by
     * Subscriber Number NAI.
     * Type:string
     * Length:1-25
     */
    private String subscriberNumber;
    
    private String externalData1;
    
    private String externalData2;

    private String adjustmentAmount;

    /**
     * @return Returns the originHostName.
     */
    public String getOriginHostName()
    {
        return originHostName;
    }
    /**
     * @param originHostName The originHostName to set.
     */
    public void setOriginHostName(String originHostName)
    {
        this.originHostName = originHostName;
    }
    /**
     * @return Returns the originNodeType.
     */
    public String getOriginNodeType()
    {
        return originNodeType;
    }
    /**
     * @param originNodeType The originNodeType to set.
     */
    public void setOriginNodeType(String originNodeType)
    {
        this.originNodeType = originNodeType;
    }
    /**
     * @return Returns the originTimeStamp.
     */
    public Date getOriginTimeStamp()
    {
        return originTimeStamp;
    }
    /**
     * @param originTimeStamp The originTimeStamp to set.
     */
    public void setOriginTimeStamp(Date originTimeStamp)
    {
        this.originTimeStamp = originTimeStamp;
    }
    /**
     * @return Returns the originTransactionID.
     */
    public String getOriginTransactionID()
    {
        return originTransactionID;
    }
    /**
     * @param originTransactionID The originTransactionID to set.
     */
    public void setOriginTransactionID(String originTransactionID)
    {
        this.originTransactionID = originTransactionID;
    }
    /**
     * @return Returns the subscriberNumber.
     */
    public String getSubscriberNumber()
    {
        return subscriberNumber;
    }
    /**
     * @param subscriberNumber The subscriberNumber to set.
     */
    public void setSubscriberNumber(String subscriberNumber)
    {
        this.subscriberNumber = subscriberNumber;
    }

    public void setExternalData1(String externalData1) {
        this.externalData1 = externalData1;
    }

    public String getExternalData1() {
        return externalData1;
    }

    public void setExternalData2(String externalData2) {
        this.externalData2 = externalData2;
    }

    public String getExternalData2() {
        return externalData2;
    }

    /**
     * @return the subscriberNumberNAI
     */
   public int getSubscriberNumberNAI() {
        return subscriberNumberNAI;
    }

    /**
     * @param subscriberNumberNAI the subscriberNumberNAI to set
     */
    public void setSubscriberNumberNAI(int subscriberNumberNAI) {
        this.subscriberNumberNAI = subscriberNumberNAI;
    }

    /**
     * @return the adjustmentAmount
     */
    public String getAdjustmentAmount() {
        return adjustmentAmount;
    }

    /**
     * @param adjustmentAmount the adjustmentAmount to set
     */
    public void setAdjustmentAmount(String adjustmentAmount) {
        this.adjustmentAmount = adjustmentAmount;
    }
}

